### ISSUE TITLE
McBoaty Upscaler - ability to process individual tiles

### ISSUE THREAD

**Issue by var1ableX** [davask/ComfyUI_MaraScott_Nodes#36]
Thanks a lot for converting into a node!

Feature request: Can a user chain these nodes such that Node A passes the tiles from its run into Node B and then is able to run B to target a specific tile with different denoise, feather settings? (~9m into Rob Adams video for details).

**Comment by davask** [comment]
Hi, you should find in the last version of the upscaler v2 the output tiles which gives you all generated tiles in the upscale process

And feel free to join AI classroom discord channel https://discord.gg/PBDzur97h5
We are a bunch of ai enthousiasmic people discussing this kind of things
