### ISSUE TITLE
Controlnet Support or IP Adapter Tiles Support

### ISSUE THREAD

**Issue by Omarsmsm** [davask/ComfyUI_MaraScott_Nodes#45]
Does the McBoaty Upscaler work if you string controlnet or Ip Adapter into it?

**Comment by davask** [comment]
Hi, It definitely works... it is still a model.. nothing special about it. Model gets influenced, ControlNets influence models... so, yes, it will hold it's shapes with a canny or depthmap...

BTW, feel free to join AI classrooms, we are a bunch of ai enthousiasmic guys and we discuss this kind of things there 
https://discord.gg/PBDzur97h5

**Comment by frankyifei** [comment]
It only works if the image is not upscale with the same size. If you upscale, it will apply original image as control to each tile. I will make another issue for this.

**Comment by davask** [comment]
Hi, I'm away until tomorrow so I could not try myself.
However you are right, now you've tested it :) I see what s happening. 
If you have a workflow for me to do my tests feel free to provide it.
